import { GoogleGenAI, Modality } from "@google/genai";

// Helper to clean base64 string
const cleanBase64 = (base64Str: string) => {
  return base64Str.replace(/^data:image\/(png|jpeg|webp);base64,/, '');
};

export const editImageWithGemini = async (
  imageBase64: string,
  promptText: string,
  mimeType: string = 'image/png'
): Promise<string> => {
  const apiKey = process.env.API_KEY;
  
  if (!apiKey) {
    throw new Error("API Key is missing. Please check your environment variables.");
  }

  const ai = new GoogleGenAI({ apiKey });

  try {
    const cleanedBase64 = cleanBase64(imageBase64);
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: promptText,
          },
          {
            inlineData: {
              data: cleanedBase64,
              mimeType: mimeType,
            },
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts && parts.length > 0) {
      // Check for inline data
      const inlineData = parts.find(p => p.inlineData);
      if (inlineData && inlineData.inlineData?.data) {
        return `data:image/png;base64,${inlineData.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};